version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.8

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  ssh2build:
    jobs:
      - docker-rpmbuild/build:
          name: centos7ssh2
          build_service: centos7ssh2
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: stream8ssh2
          build_service: stream8ssh2
          bintray_uploader: stream8bintray
      - docker-rpmbuild/build:
          name: centos7ssh2php81
          build_file: docker-compose.php81.yml
          build_service: centos7ssh2php81
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: stream8ssh2php81
          build_file: docker-compose.php81.yml
          build_service: stream8ssh2php81
          bintray_uploader: stream8bintray
